### PR TITLE
fix events.follow() to actually set notes

### PR DESCRIPTION
**Pull request by staltz**
The 1st test in `test/index.js` didn't pass. Others did

### CODE REVIEW

**Comment by staltz** [comment]
While you review this, I'll try to make a test that fails on the previous implementation.

Don't merge yet

**Comment by arj03** [comment]
Fix looks good. I found a minor lseq cleanup while looking at how this is handled in this file. Two line change. I can open a PR on top of this?

**Comment by staltz** [comment]
@arj03 Sure!

**Comment by staltz** [comment]
Note though, this PR is now deprecated since I cherry-picked the commit so that we start with the test. See #46

**Pull request closed without merging**
